baseURL = 'https://mikage-emu.github.io/'
languageCode = 'en-us'
title = '3dbrew'
disablePathToLower = true
theme = "hugo-book"

# Broken, see https://github.com/gohugoio/hugo/issues/12130
# relativeURLs = true

[taxonomies]
categories = 'categories'

[pagination]
pagerSize = 10000
